# -*- coding: utf-8 -*-
"""Day5_HF_Pulls.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19xNVdMpmnuiyqzljzmSNo74O4nvIEFnm
"""

!pip install -q transformers requests sentence-transformers

import os
import getpass

if 'HF_TOKEN' not in os.environ:
    os.environ['HF_TOKEN'] = getpass.getpass('HF token (read scope): ')

# Note: API endpoint could not be resolved in this Colab runtime.
# Local inference was used for completion of the lab.
import os
import requests
import time

HF_TOKEN = os.environ['HF_TOKEN']

def hf_zero_shot_api(text, labels):
    r = requests.post(
        'https://api-inference.huggingface.co/models/facebook/bart-large-mnli',
        headers={'Authorization': f'Bearer {HF_TOKEN}'},
        json={
            'inputs': text,
            'parameters': {
                'candidate_labels': labels
            }
        }
    )
    return r.json()

# Sample resumes
resumes = [
    'Built React dashboards for 3 startups',
    'Implemented Spring Boot microservices in Java for fintech app',
    'Trained CNN for image classification using PyTorch, 87% accuracy',
    'Cleaned 100k row dataset using pandas + plotted in seaborn for monthly reports',
    'Wrote SQL queries against PostgreSQL, optimised 3 slow queries by 10x'
]

labels = [
    'frontend dev',
    'backend dev',
    'data analyst',
    'ML engineer'
]

start = time.time()

for r in resumes:
    result = hf_zero_shot_api(r, labels)

    if 'error' in result:
        print("Error:", result['error'])
    else:
        print(
            f'{r[:50]:50} -> '
            f'{result["labels"][0]} '
            f'({result["scores"][0]:.2f})'
        )

print(f'\nAPI time: {time.time()-start:.2f}s')

# Local Model Loading
from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

print("Model loaded successfully!")

#Resume Classification
import time

resumes = [
    'Built React dashboards for 3 startups',
    'Implemented Spring Boot microservices in Java for fintech app',
    'Trained CNN for image classification using PyTorch, 87% accuracy',
    'Cleaned 100k row dataset using pandas + plotted in seaborn for monthly reports',
    'Wrote SQL queries against PostgreSQL, optimised 3 slow queries by 10x'
]

labels = [
    'frontend dev',
    'backend dev',
    'data analyst',
    'ML engineer'
]

start = time.time()

for r in resumes:
    result = classifier(r, candidate_labels=labels)

    print(
        f'{r[:50]:50} -> '
        f'{result["labels"][0]} '
        f'({result["scores"][0]:.2f})'
    )

print(f'\nLocal time: {time.time()-start:.2f}s')

# Sentiment Analysis
from transformers import pipeline

sentiment = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

answers = [
    'I really enjoyed working on the team and shipped 3 features.',
    'I was the only one writing code; everyone else was slow.',
    'I learned a lot from my mentor and grew technically.',
    "I had to redo most of my teammate's work because it was wrong.",
    'My internship was great — would recommend it to anyone.'
]

print("Sentiment scores:\n")

for a in answers:
    result = sentiment(a)[0]

    print(
        f'[{result["label"]} {result["score"]:.2f}] '
        f'{a}'
    )

# Timing Comparison
import time

def time_call(fn, n_runs=3):
    times = []

    for _ in range(n_runs):
        start = time.time()
        fn()
        times.append(time.time() - start)

    return min(times), sum(times)/len(times)

def call_local():
    classifier(
        "Built React dashboards",
        candidate_labels=["frontend dev", "backend dev"]
    )

local_min, local_avg = time_call(call_local)

print("Inference Timing")
print("-" * 30)
print(f"Local min: {local_min:.2f}s")
print(f"Local avg: {local_avg:.2f}s")